language: node_js
node_js:
 - "10.10"

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - node_modules

script:
  - ng build --prod


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist
  on:
    branch: master
